STLTaxAuctionMap/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("maps/", include('maps.urls')),
    path('', include('pages.urls')),
    path('dashboards/', include('dashboards.urls')),
]

dashboards/urls.py
from django.urls import path
from .views import StLouisLandTaxDashboard2022, LRADashboard, StLouisLandTaxDashboard2023, StCharlesCountyLandTaxDashboard

app_name = 'dashboards'

urlpatterns = [
    path("2022StLouisLandTaxDashboard", StLouisLandTaxDashboard2022.as_view(), name="2022StLouisLandTaxDashboard"),
    path("2023StLouisLandTaxDashboard", StLouisLandTaxDashboard2023.as_view(), name="2023StLouisLandTaxDashboard"),
    path("2022LRADashboard", LRADashboard.as_view(), name="2022LRADashboard"),
    path("2022StCharlesCountyLandTaxDashboard", StCharlesCountyLandTaxDashboard.as_view(), name="StCharlesCountyLandTaxDashboard")
]

maps/urls.py
from django.urls import path
from . import views

app_name = 'maps'

urlpatterns = [
    path("2022StLouisLandTaxMap", views.combinedView, name='StLouisCityLandTaxSale'),
    path("2023StLouisLandTaxMap", views.combinedViewSTL2023, name='StLouisCityLandTaxSale2023'),
    path("LRAMap", views.LRAcombinedView, name='LRA'),
    path("2023StCharlesTaxMap", views.StCharles2023combinedView, name='StCharles2023')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="ThemeStarz">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'fonts/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/bootstrap-select.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/jquery.slider.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/MarkerCluster.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css"
          type="text/css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" type="text/css">
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <title>STL Tax Auction Map</title>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-Z8LRS38QCZ"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'UA-203130756-1');
    </script>
</head>
<body class="page-homepage map-leaflet" id="page-top" data-spy="scroll" data-target=".navigation" data-offset="90">
<div class="navigation">
    <div class="container">
        <header class="navbar" id="top" role="banner">
            <div class="navbar-header">
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-brand nav" id="brand">
                    <a href="{% url 'home' %}"><img src="{% static 'img/Logo.png' %}" alt="brand"
                                                    style="width: 75px;height: 75px;"></a>
                </div>
            </div>
            <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Homepage</a></li>
                    <li class="has-child"><a href="{% url 'home' %}">Maps</a>
                        <ul class="child-navigation">
                            <li class="has-child"><a href="{% url 'home' %}">St Louis City</a>
                                <ul class="child-navigation">
                                    <li><a href="{% url 'maps:StLouisCityLandTaxSale2023' %}">2023 St Louis City Land
                                        Tax Sales</a></li>
                                    <li><a href="{% url 'maps:LRA' %}">Land Reutilization Authority</a></li>
                                    <li><a href="{% url 'maps:StLouisCityLandTaxSale' %}">2022 St Louis City Land Tax
                                        Sales</a></li>
                                </ul>
                            <li><a href="{% url 'maps:StCharles2023' %}">St Charles County</a></li>
                        </ul>
                    </li>
                    <li class="has-child"><a href="#">Dashboards</a>
                        <ul class="child-navigation">
                            <li class="has-child"><a href="#">St Louis City</a>
                                <ul class="child-navigation">
                                    <li><a href="{% url 'dashboards:2023StLouisLandTaxDashboard' %}">2023 St Louis City
                                        Land Tax Sales</a></li>
                                    <li><a href="{% url 'dashboards:2022LRADashboard' %}">2022 Land Reutilization
                                        Authority</a></li>
                                    <li><a href="{% url 'dashboards:2022StLouisLandTaxDashboard' %}">2022 St Louis City
                                        Land Tax Sales</a></li>
                                </ul>
                            <li class="has-child"><a href="{% url 'dashboards:StCharlesCountyLandTaxDashboard' %}">St Charles County</a>
                        </ul>
                    </li>
                    <li><a href="{% url 'about' %}">About</a></li>
                    <li><a href="{% url 'faq' %}">FAQ</a></li>
                    <li><a href="{% url 'donate' %}">Donate</a></li>
                    <li><a href="{% url 'contact' %}">Contact</a></li>
                    <li><a href="{% url 'terms' %}">Terms of Services</a></li>
                </ul>
            </nav><!-- /.navbar collapse-->
        </header><!-- /.navbar -->
    </div><!-- /.container -->
</div><!-- /.navigation -->
{% block content %}

{% endblock content %}
<script type="text/javascript" src="{% static 'js/jquery-2.1.0.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/smoothscroll.js' %}"></script>
<script type="text/javascript" src="{% static 'js/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-select.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.validate.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.placeholder.js' %}"></script>
<script type="text/javascript" src="{% static 'js/icheck.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.vanillabox-0.1.5.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/retina-1.1.0.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/smoothscroll.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jshashtable-2.1_src.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.numberformatter-1.2.3.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.numberformatter-1.2.3.js' %}"></script>
<script type="text/javascript" src="{% static 'js/tmpl.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.dependClass-0.1.js' %}"></script>
<script type="text/javascript" src="{% static 'js/draggable-0.1.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.slider.js' %}"></script>
<script type="text/javascript" src="{% static 'js/custom-map.js' %}"></script>
<script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
</body>
<div class="wrapper">
    <footer id="page-footer">
        <div class="inner">
            <aside id="footer-main">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 col-sm-4">
                            <article>
                                <h3>About Us</h3>
                                <p>The primary objective of the STL Tax Auction Map is to enhance transparency and
                                    facilitate potential investors' understanding of the Land Tax Sales in St. Louis and
                                    its nearby regions. This platform was specifically designed to introduce interested
                                    parties to the auction process and provide them with valuable insights to make
                                    informed investment decisions.</p>
                                <hr>
                                <a href="{% url 'about' %}" class="link-arrow">Read More</a>
                            </article>
                        </div><!-- /.col-sm-3 -->
                        <div class="col-md-4 col-sm-4">
                            <article>
                                <h3>Contact</h3>
                                <address>
                                    <strong>STL Tax Auction Map</strong><br>
                                    St Louis, MO
                                </address>
                                <a href="mailto: stltaxauctionmap@gmail.com">stltaxauctionmap@gmail.com</a>
                            </article>
                        </div><!-- /.col-sm-3 -->
                        <div class="col-md-4 col-sm-4">
                            <article>
                                <h3>Useful Links</h3>
                                <ul class="list-unstyled list-links">
                                    <li>
                                        <a href="https://www.stlouis-mo.gov/government/departments/sheriff/land-tax-sales.cfm"
                                           target="_blank">St Louis City Land Tax Sale Dates</a></li>
                                    <li><a href="https://mostlouiscity.fidlar.com/MOStLouis/DirectSearch/#/search"
                                           target="_blank">St Louis City Lien Search</a></li>
                                    <li><a href="https://missouritaxsales.com/" target="_blank">Sweet Law Office
                                        Missouri Tax Sales</a></li>
                                    <li><a href="{% url 'faq' %}">FAQ</a></li>
                                    <li><a href="{% url 'terms' %}">Terms and Conditions</a></li>
                                </ul>
                            </article>
                        </div><!-- /.col-sm-3 -->
                    </div><!-- /.row -->
                </div><!-- /.container -->
            </aside><!-- /#footer-main -->
            <aside id="footer-thumbnails" class="footer-thumbnails"></aside><!-- /#footer-thumbnails -->
            <aside id="footer-copyright">
                <div class="container">
                    <span>Copyright © 2022. All Rights Reserved.</span>
                    <span class="pull-right"><a href="#page-top" class="roll">Go to top</a></span>
                </div>
            </aside>
        </div><!-- /.inner -->
    </footer>
</div>
</html>